"""add store table, add FK to product seller/category

Revision ID: 064d1b4131c1
Revises: c13329e37e4f
Create Date: 2026-08-12 13:22:55.587563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '064d1b4131c1'
down_revision: Union[str, Sequence[str], None] = 'c13329e37e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('seller_id', sa.String(length=36), nullable=False))
    op.add_column('products', sa.Column('category_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_seller_id'), 'products', ['seller_id'], unique=False)
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'products', 'users', ['seller_id'], ['id'])
    op.add_column('users', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('photoprofil', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'status')
    op.drop_column('users', 'photoprofil')
    op.drop_column('users', 'address')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_seller_id'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_column('products', 'category_id')
    op.drop_column('products', 'seller_id')
    op.drop_column('categories', 'image')
    # ### end Alembic commands ###
